SamarthTMSL/HacktoberFest-Projects-and-games

color-generator/pointergame.css, color-generator/pointergame.html, color-generator/pointergame.html.bak
Fun application of html and css
=> COLOURFUL POINTER GAME

Gym Website/index.html
Solve issue #22 
Adding Validate Logic
=> Adding Validate Logic to web

Low Battery Alert System/BatteryNotif.py, Low Battery Alert System/ReadMe.md, Low Battery Alert System/requirements.txt
Thank you for reading my pull request
=> Low Battery Alert System

Number_guessing_game/index.html
Solve issue #33
#HacktoberFest 2022
=> Adding Hint Box in Game

Number_guessing_game/script.js
Solve issue #34
#HacktoberFest 2022
=> Adding Logic to Hint Box

Number_guessing_game/style.css
Solve issue #35
#HacktoberFest 2022
=> Adding Style to Hint Box and enhance style

Counter/index.html, Counter/script.js, Counter/style.css
=> Added a Counter Website

Food-ordering-website/index.css, Food-ordering-website/index.html, Food-ordering-website/phone.css
Updated the Card section
Added mobile responsive footer section
=>  Mobile Responsive Card Section updated and Footer Section Added

digital_clock.py
=> digital_clock.py

BackgroundColorChanger/hex.html, BackgroundColorChanger/index.html, BackgroundColorChanger/script.js, BackgroundColorChanger/script1.js, BackgroundColorChanger/simple.html, BackgroundColorChanger/style.css
Added a Background Color Changing Website that changes Background color and also gives the Hex value of that particular colour.
=> Added a Background Color Changing Website

Dice Roll Simulator with Python.py
Please accept and marge my PR with Hacktoberfest label
=> Dice Roll Simulator with Python

suduko_solver.py
for contributing to hacktober fest.
=> suduko_solver.py

Mini_Voting_System/ELECTION.H, Mini_Voting_System/MAIN.C, Mini_Voting_System/README.md
I have added a mini voting system project.
Please accept and merge my PR.
=> Added Mini Voting System Project

Pong Game in Python
=> Create Pong Game in Python

Countdown Calculator/Countdown_Calc.py, Countdown Calculator/Readme.md
=> Added a countdown calculator made in Python

QUIZ GAME IN PYTHON
=> Python QUIZ Game in Python

Rock_Paper_Scissors_Lizard_Spock.py
I added a Rock_Paper_Scissors_Lizard_Spock game in python, inspired by Dr. Sheldon Cooper!
=> Added Rock_Paper_Scissors_Lizard_Spock game

hangman.py
Added a hangman game in python!
=> Added hangman game in python

word_replace.py
Added word_replacement game in python.
=> Added word_replacement game in python

calc.py
Added basic calculator in python which performs basic functions like addition, subtraction, division, multiplication.
=> Added basic calculator in python

Student-Enrollment-Form/index.html, Student-Enrollment-Form/script.css, Student-Enrollment-Form/style.css
=> Added "Student-Enrollment-Form" project !

Automorphic_No_Finder.c
I made a C program that check whether the inputted no. is an Automorphic no or not! Its not a game, but can be implemented as a Project for checking inputted no. is Automorphic or not. #3
=> Automorphic No Checker

PokemonSelector.py
It grants a you an unique pokemon everytime you run it! #3
=> PokemonSelectorGame

Text translator Using Python
=> Create Text translator Using Python
